### ISSUE TITLE
日本語のurlが醜くて長い

### ISSUE THREAD

**Issue by karino2** [saneyuki/github-issue2markdown#4]
現状、URLが日本語になるので、url encodeすると長くてださい。

https://karino2.github.io/2017/09/22/%E3%83%81%E3%83%BC%E3%83%A0%E7%9A%84%E3%81%AA%E4%BA%8B%E3%81%AB%E3%81%82%E3%81%BE%E3%82%8A%E5%8F%A3%E3%82%92%E5%87%BA%E3%81%95%E3%81%AA%E3%81%84%E5%88%A9%E7%82%B9.html

yamlのtitleにtitle:で指定されているので、日付のあとのファイル名の部分はなんでも良さそう。
生成の都度issueから同じ名前になる必要はあるが、生成時のissueのidとかissue番号とか、短い奴に置き換えたい（日付の部分は必須らしいので、_posts/2017-09-22-123456.md とかが良さそう)

参考の為のテスト用commit:
https://github.com/karino2/karino2.github.io/commit/f57e0ae67b0d9c434682cafbab58465522fc3315

**Comment by karino2** [comment]
https://karino2.github.io/2017/09/22/123456.html

こんなURLになってる。

**Comment by tetsuharuohzeki** [comment]
issue番号にしますか. ユニークだし.

**Comment by karino2** [comment]
せやね。それが良さそう。

**Comment by karino2** [comment]
動いてそうです。サンクス！
